[window]
opacity = 0.9

[font]
size = 16

[font.normal]
family = "FiraCode Nerd Font Mono"

[[keyboard.bindings]]
chars = "\u001BF"
key = "Right"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001BB"
key = "Left"
mods = "Alt"

